/*
 *  Copyright 2013 SERLI (www.serli.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 * 
 */

package org.gololang.netbeans;


import java.io.File;
import javax.swing.JFileChooser;
import org.openide.util.NbPreferences;

final class RunPanel extends javax.swing.JPanel {

  private final RunOptionsPanelController controller;

  RunPanel(RunOptionsPanelController controller) {
    this.controller = controller;
    initComponents();
    controller.changed();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    rootDirFileChooser = new javax.swing.JFileChooser();
    jLabel1 = new javax.swing.JLabel();
    rootDirTextField = new javax.swing.JTextField();
    changeButton = new javax.swing.JButton();

    rootDirFileChooser.setFileFilter(null);
    rootDirFileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

    org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(RunPanel.class, "RunPanel.jLabel1.text")); // NOI18N

    rootDirTextField.setText(org.openide.util.NbBundle.getMessage(RunPanel.class, "RunPanel.rootDirTextField.text")); // NOI18N
    rootDirTextField.setEnabled(false);

    org.openide.awt.Mnemonics.setLocalizedText(changeButton, org.openide.util.NbBundle.getMessage(RunPanel.class, "RunPanel.changeButton.text")); // NOI18N
    changeButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        changeButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1))
          .addGroup(layout.createSequentialGroup()
            .addGap(60, 60, 60)
            .addComponent(rootDirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(changeButton)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(rootDirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(changeButton))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
    if (rootDirFileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
      rootDirTextField.setText(rootDirFileChooser.getSelectedFile().getAbsolutePath());
      controller.changed();
    };
  }//GEN-LAST:event_changeButtonActionPerformed

  void load() {
    rootDirTextField.setText(NbPreferences.forModule(RunPanel.class).get("rootDir", ""));
  }

  void store() {
    NbPreferences.forModule(RunPanel.class).put("rootDir", rootDirTextField.getText());
  }

  boolean valid() {
    File rootDirFile = new File(rootDirTextField.getText());
    if (!rootDirFile.exists()) {
      return false;
    }
    if (!new File(rootDirFile, "bin" + File.separator + "golo").exists()) {
      return false;
    }
    return true;
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton changeButton;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JFileChooser rootDirFileChooser;
  private javax.swing.JTextField rootDirTextField;
  // End of variables declaration//GEN-END:variables
}
